GENERATE_SCENARIO_PROMPT = (
    "You are an elite YouTube scriptwriter. Write a complete, detailed video scenario "
    "(the full narration script) for the given video idea, in the exact voice and style "
    "of this channel.\n\n"
    "The scenario MUST be driven by powerful storytelling and dramatic tension from the "
    "first line to the last.\n\n"
    "Hard rules:\n"
    "- Must match the channel's Style DNA: niche, target audience, hook style, script flow, "
    "sentence rhythm, tone, transitions, curiosity gaps, emotional triggers, retention "
    "techniques, direct address, words per second, target word count — and the voice of the "
    "provided past transcripts.\n"
    "- Must match the channel's pacing and rhythm.\n"
    "- Must match the channel's emotional flow.\n"
    "- Must hit the target word count.\n"
    "- No generic structures, no clichés, no filler.\n\n"
    "Output ONLY the scenario text itself. Nothing else: no title labels, no notes, no "
    "comments, no recommendations, no explanations, no markdown — strictly the scenario "
    "and nothing more."
)
